#!/bin/sh
### BEGIN INIT INFO
# Provides: Creates Oracle mount point # Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Used for Oracle installation # Description: Used for Oracle installation 
### END INIT INFO

# Aktionen
case "$1" in 
    start)
        mkdir /var/lock/subsys 2>/dev/null 
        touch /var/lock/subsys/listener 
        rm /dev/shm 2>/dev/null
        mkdir /dev/shm 2>/dev/null
        mount -t tmpfs shmfs -o size=2048m /dev/shm
        ;; 
    stop)
        ;; 
    restart)
        ;;
esac 
exit 0
